import './globals.css';

import { Analytics } from '@vercel/analytics/react';
import { Epilogue } from 'next/font/google';
import type { Metadata } from 'next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { cn } from '@/utils';

const font = Epilogue({ style: ['normal', 'italic'], subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Hieu Nhan',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={cn(font.className, 'flex justify-center')}>
      {children}
      <Analytics />
      <SpeedInsights />
    </body>
  </html>
);

export default RootLayout;
